### ISSUE TITLE
BITS VIB events (again)

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS_scrapers#23]
The BITSVIB people are writing JSONLD expressions of all their things. 
Would be worth replacing the existing BITS scraper with one for this feed. http://dev.bits.vib.be/eulife/all_events-vib_conferences.json 
Keep the old data and associate any new stuff with the new old content providerr

**Comment by fbacall** [comment]
Don't we already do this? https://github.com/ElixirUK/TeSS_scrapers/blob/master/app/scrapers/bitsvib_events_jsonld_scraper.rb
