### ISSUE TITLE
Checkout IFB scraper

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS_scrapers#24]
a) scraper hasn't been run in a long while

b) Duplicate records for some materials https://tess.elixir-europe.org/materials?content_provider=IFB+French+Institute+of+Bioinformatics&page=3

c) New scraper for events  - https://www.france-bioinformatique.fr/en/evenements_upcoming

**Comment by fbacall** [comment]
Some malformed HTML (around the author bits) breaks the parser.

Doctype is wrong, should be RDF1.1 - stops licenses being extracted
